server:
  port: 8080
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/chap_db
    username: chap_user
    password: chap_pw 
    driver-class-name: com.mysql.cj.jdbc.Driver



docker:
  compose:
    enabled: false

jpa:
  database-platform: org.hibernate.dialect.MySQL8Dialect
  hibernate:
    ddl-auto: update # 배포 시 변경



app:
  auth:
    jwt:
      secret: PUKKZtxBepIAHyTvGiLchqESyBlumrofLcwsQe7phdA=     # 256bit 이상
      access-exp-sec: 3600
      refresh-exp-sec: 86400

  kakao:
    local:
      base-url: https://dapi.kakao.com
      rest-api-key: ${KAKAO_REST_API_KEY}

logging:
  level:
    root: INFO
    org.chapchap.be: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    try-it-out-enabled: true
    filter: true
