server:
  port: 8080
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:mysql://mysql_chap_chap:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 배포 시 변경

app:
  # 배포 환경
  web:
    cross-site: true    # 프론트/Swagger가 다른 도메인
    cookie-domain: ".shallwewalk.kro.kr"  # 공통 상위 도메인
  cors:
    allowed-origins:
      - "https://shallwewalk.kro.kr"
      - "https://www.shallwewalk.kro.kr"

#  # 로컬 환경
#  web:
#    cross-site: false   # 같은 오리진
#    cookie-domain: ""   # 비워두면 도메인 지정 안 함(로컬)
#  cors:
#    allowed-origins:
#      - "http://localhost:3000, http://localhost:8078"

  auth:
    jwt:
      secret: ${JWT_SECRET}       # 256bit 이상
      access-exp-sec: ${JWT_ACCESS_EXP_SEC}
      refresh-exp-sec: ${JWT_REFRESH_EXP_SEC}

  routes:
    ors:
      base-url: ${ORS_BASE_URL}
      api-key: ${ORS_API_KEY}

logging:
  level:
    root: INFO
    org.chapchap.be: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    try-it-out-enabled: true
    filter: true
    with-credentials: true
