server:
  port: 8080
  forward-headers-strategy: native

spring:
  datasource:
    url: jdbc:mysql://mysql_chap_chap:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update # 배포 시 변경

app:
  auth:
    jwt:
      secret: ${JWT_SECRET}       # 256bit 이상
      access-exp-sec: ${JWT_ACCESS_EXP_SEC}
      refresh-exp-sec: ${JWT_REFRESH_EXP_SEC}

  google:
    routes:
      base-url: https://routes.googleapis.com
      api-key: ${GOOGLE_MAPS_API_KEY}

logging:
  level:
    root: INFO
    org.chapchap.be: INFO

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-operation-id: true
    tags-sorter: alpha
    operations-sorter: method
    doc-expansion: none
    try-it-out-enabled: true
    filter: true
